In [2]:
import numpy as np

arr = np.array([1,2,3,5])

print(arr)
type(arr)

[1 2 3 5]


numpy.ndarray

In [3]:
arr

array([1, 2, 3, 5])

In [4]:
## 2D array

arr2 = np.array([[1,2,34,],[23,45,56]])

arr2

array([[ 1,  2, 34],
       [23, 45, 56]])

In [5]:
## 3D array

arr3 = np.array([[[1,2,3],[4,5,6]],[[12,13,14],[23,34,45]]])

arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12, 13, 14],
        [23, 34, 45]]])

In [7]:
arr0 = np.array(42)
arr0

array(42)

In [9]:
## Checking Dimensions of array

print(arr0.ndim)
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3
