In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
for x in arr:
    print(x)

1
2
3
4
5


In [4]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
for x in arr1:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [6]:
for i in arr1:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8


# Slicing

In [7]:
arr[1:4]

array([2, 3, 4])

In [13]:
arr[2:5]

array([3, 4, 5])

In [10]:
arr[1:]

array([2, 3, 4, 5])

In [14]:
arr[:3]

array([1, 2, 3])

In [15]:
arr[0:4:2]

array([1, 3])


# Slicing 2D Array

In [17]:
arr1[1,0:2]

array([5, 6])