In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3,3,4,5,8,5,10,20,1])

In [9]:
x = np.where(a == 1)

In [10]:
x

(array([ 0, 10], dtype=int64),)

In [11]:
y = np.where(a == 4)

In [12]:
y

(array([4], dtype=int64),)

In [13]:
even = np.where(a%2 == 0)

In [14]:
even

(array([1, 4, 6, 8, 9], dtype=int64),)

In [15]:
np.sort(a)

array([ 1,  1,  2,  3,  3,  4,  5,  5,  8, 10, 20])

In [16]:
fruits = np.array(["mango","papaya","apple","orange"])

In [17]:
np.sort(fruits)

array(['apple', 'mango', 'orange', 'papaya'], dtype='<U6')