In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr.shape

(5,)

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr2.shape

(2, 3)

In [6]:
 arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [7]:
newarr = arr3.reshape(4,3)

In [8]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
newarr.shape

(4, 3)

In [10]:
arr3.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr3.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [13]:
## Flatening of array

flat_arr = newarr.reshape(-1)
flat_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
flat_arr.shape

(12,)